a=input("Enter the list1 of colours seperated by a comma ::")
b=input("Enter the list2 of colours seperated by a comma ::")
list_1=a.split(",")
list_2=b.split(",")
set_1=set(list_1)
set_2=set(list_2)
u=set_1.difference(set_2)
o=list(u)
print(o)
